### ISSUE TITLE
page-query.js error when the folder "dummy" was removed

### ISSUE THREAD

**Issue by Lynn-Speng** [cossssmin/gridsome-starter-bleda#86]
Hi, I am new to Gridsome and thank you for developing such a nice starter.
A interesting errer occurs when I removed the folder "dummy". 
The error log is here:
```
# lynn @ lynn-archlinux in ~/Blog [0:05:45] C:130
$ gridsome develop
Gridsome v0.7.15

Initializing plugins...
Load sources - 0.04s
Create GraphQL schema - 0.09s
 ERROR  Failed to compile with 4 errors                                                                                 12:06:02 AM

 error  in ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "description" on type "Post".

GraphQL request:80:9
79 |         excerpt
80 |         description
   |         ^
81 |         path
    at Object.module.exports (/home/lynn/Blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query 1:0-331 1:347-350 1:352-680 1:352-680
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/Tag.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "description" on type "Post".

GraphQL request:98:13
97 |             excerpt
98 |             description
   |             ^
99 |             timeToRead
    at Object.module.exports (/home/lynn/Blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/templates/Tag.vue?vue&type=custom&index=0&blockType=page-query 1:0-329 1:345-348 1:350-676 1:350-676
 @ ./src/templates/Tag.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/Post.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "slug" on type "Post".

GraphQL request:143:5
142 |     path
143 |     slug
    |     ^
144 |     datetime: date (format: "YYYY-MM-DD HH:mm:ss")
    at Object.module.exports (/home/lynn/Blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/templates/Post.vue?vue&type=custom&index=0&blockType=page-query 1:0-330 1:346-349 1:351-678 1:351-678
 @ ./src/templates/Post.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/Author.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "title" on type "Author".

GraphQL request:80:5
79 |     id
80 |     title
   |     ^
81 |     path
    at Object.module.exports (/home/lynn/Blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/templates/Author.vue?vue&type=custom&index=0&blockType=page-query 1:0-332 1:348-351 1:353-682 1:353-682
 @ ./src/templates/Author.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js



 WAIT  Compiling...                                                                                                     12:06:02 AM



 ERROR  Failed to compile with 4 errors                                                                                 12:06:03 AM

 error  in ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "description" on type "Post".

GraphQL request:80:9
79 |         excerpt
80 |         description
   |         ^
81 |         path
    at Object.module.exports (/home/lynn/Blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/pages/Index.vue?vue&type=custom&index=0&blockType=page-query 1:0-331 1:347-350 1:352-680 1:352-680
 @ ./src/pages/Index.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/Tag.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "description" on type "Post".

GraphQL request:98:13
97 |             excerpt
98 |             description
   |             ^
99 |             timeToRead
    at Object.module.exports (/home/lynn/Blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/templates/Tag.vue?vue&type=custom&index=0&blockType=page-query 1:0-329 1:345-348 1:350-676 1:350-676
 @ ./src/templates/Tag.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/Post.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "slug" on type "Post".

GraphQL request:143:5
142 |     path
143 |     slug
    |     ^
144 |     datetime: date (format: "YYYY-MM-DD HH:mm:ss")
    at Object.module.exports (/home/lynn/Blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/templates/Post.vue?vue&type=custom&index=0&blockType=page-query 1:0-330 1:346-349 1:351-678 1:351-678
 @ ./src/templates/Post.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js

 error  in ./src/templates/Author.vue?vue&type=custom&index=0&blockType=page-query

Module build failed (from ./node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js):
Error: Cannot query field "title" on type "Author".

GraphQL request:80:5
79 |     id
80 |     title
   |     ^
81 |     path
    at Object.module.exports (/home/lynn/Blog/node_modules/gridsome/lib/plugins/vue-components/lib/loaders/page-query.js:29:23)

 @ ./src/templates/Author.vue?vue&type=custom&index=0&blockType=page-query 1:0-332 1:348-351 1:353-682 1:353-682
 @ ./src/templates/Author.vue
 @ ./src/.temp/routes.js
 @ ./node_modules/gridsome/app/router.js
 @ ./node_modules/gridsome/app/entry.sockjs.js
 @ multi webpack/hot/dev-server webpack-hot-middleware/client?name=app&reload=true&noInfo=true ./node_modules/gridsome/app/entry.client.js ./node_modules/gridsome/app/entry.sockjs.js
```

This is the the tree of the fold "content:
```
content
└── posts
    └── Life
        └── 2020-06-08-try-gridsome.md
```

And what is in this post is:
```
---
title: "try-gridsome"
date: 2020-06-08 22:16:52
tags:
    - Life
fullscreen: true
---
Hello World
```
When I move the "dummy" back, these errors are all gone :)
Thanks in advance.

**Comment by Lynn-Speng** [comment]
I plan to learn Vue.js :D
